#ifndef _MINECRAFT_NETWORK_PACKET_H_
#define _MINECRAFT_NETWORK_PACKET_H_

// VoxelForge: Multiplayer removed. Packet IDs kept for level event compatibility.

enum MinecraftPacketIds
{
	PACKET_KEEPALIVE = 0,
	PACKET_LOGIN,
	PACKET_LOGINSTATUS,
	PACKET_READY,
	PACKET_MESSAGE,
	PACKET_SETTIME,
	PACKET_STARTGAME,
	PACKET_ADDMOB,
	PACKET_ADDPLAYER,
	PACKET_REMOVEPLAYER,
	PACKET_TELEPORTENTITY,
	PACKET_ADDENTITY,
	PACKET_REMOVEENTITY,
	PACKET_ADDITEMENTITY,
	PACKET_TAKEITEMENTITY,
	PACKET_MOVEENTITY,
	PACKET_MOVEENTITY_POS,
	PACKET_MOVEENTITY_ROT,
	PACKET_MOVEENTITY_POSROT,
	PACKET_MOVEPLAYER,
	PACKET_PLACEBLOCK,
	PACKET_REMOVEBLOCK,
	PACKET_UPDATEBLOCK,
	PACKET_ADDPAINTING,
	PACKET_EXPLODE,
	PACKET_LEVELEVENT,
	PACKET_TILEEVENT,
	PACKET_ENTITYEVENT,
	PACKET_REQUESTCHUNK,
	PACKET_CHUNKDATA,
	PACKET_PLAYEREQUIPMENT,
	PACKET_PLAYERARMOREQUIPMENT,
	PACKET_INTERACT,
	PACKET_USEITEM,
	PACKET_PLAYERACTION,
	PACKET_UPDATEARMOR,
	PACKET_HURTARMOR,
	PACKET_SETENTITYDATA,
	PACKET_SETENTITYMOTION,
	PACKET_SETHEALTH,
	PACKET_SETSPAWNPOSITION,
	PACKET_ANIMATE,
	PACKET_RESPAWN,
	PACKET_SENDINVENTORY,
	PACKET_DROPITEM,
	PACKET_CONTAINEROPEN,
	PACKET_CONTAINERCLOSE,
	PACKET_CONTAINERSETSLOT,
	PACKET_CONTAINERSETDATA,
	PACKET_CONTAINERSETCONTENT,
	PACKET_CONTAINERACK,
	PACKET_CHAT,
	PACKET_SIGNUPDATE,
	PACKET_ADVENTURESETTINGS,
	PACKET_END_ID
};

const int NUM_PACKETS = PACKET_END_ID;

#endif
